=== kba/culturegraph-metamorph/src/main/resources/metamorph.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns:tns="http://www.culturegraph.org/metamorph"
	targetNamespace="http://www.culturegraph.org/metamorph" xmlns="http://www.w3.org/2001/XMLSchema">

	<include schemaLocation="" />

	<element name="metamorph">
		<complexType>
			<sequence minOccurs="1" maxOccurs="1">
				<element ref="tns:name" maxOccurs="1" minOccurs="0" />
				<element ref="tns:annotation" maxOccurs="1" minOccurs="0" />
				<element ref="tns:entity" maxOccurs="unbounded" minOccurs="0" />
				<choice maxOccurs="unbounded" minOccurs="0">
					<element ref="tns:group" />
					<element ref="tns:collect-literal" />
					<element ref="tns:collect-entity" />
					<element ref="tns:data" />
				</choice>
				<element ref="tns:map" minOccurs="0" maxOccurs="unbounded" />
			</sequence>
			<attribute name="entityMarker">
				<simpleType>
					<restriction base="string">
						<length value="1"></length>
					</restriction>
				</simpleType>
			</attribute>
		</complexType>
	</element>

	<element name="name" type="string" />
	<element name="annotation" type="string" />

	<element name="group">
		<complexType>
			<sequence>
				<element ref="tns:annotation" minOccurs="0" maxOccurs="1" />
				<choice minOccurs="1" maxOccurs="unbounded">
					<element ref="tns:collect-literal" minOccurs="0" maxOccurs="unbounded" />
					<element ref="tns:data" minOccurs="0" maxOccurs="unbounded" />
				</choice>
			</sequence>
			<attribute name="name" type="string" use="optional" />
			<attribute name="value" type="string" use="optional" />
		</complexType>
	</element>

	<element name="collect-literal">
		<complexType>
			<sequence>
				<element ref="tns:annotation" minOccurs="0" maxOccurs="1" />
				<element ref="tns:data" minOccurs="2" maxOccurs="unbounded" />
				<group ref="tns:function" minOccurs="0" maxOccurs="unbounded"/>
			</sequence>
			<attribute name="name" type="string" use="optional" />
			<attribute name="value" type="string" use="optional" />

			<attribute name="reset" type="boolean" use="optional"
				default="false" />
			<attribute name="sameEntity" type="boolean" use="optional"
				default="false" />
			<attribute name="forceOnEnd" type="string" use="optional" />
		</complexType>
	</element>

	<element name="collect-entity">
		<complexType>
			<sequence>
				<element ref="tns:annotation" minOccurs="0" maxOccurs="1" />
				<element ref="tns:data" minOccurs="1" maxOccurs="unbounded" />
			</sequence>
			<attribute name="name" type="string" use="required" />
			<attribute name="reset" type="boolean" use="optional"
				default="false" />
			<attribute name="sameEntity" type="boolean" use="optional"
				default="false" />
			<attribute name="forceOnEnd" type="string" use="optional" />
		</complexType>
	</element>

	<element name="data">
		<complexType>
			<sequence>
				<element ref="tns:annotation" minOccurs="0" maxOccurs="1" />
				<group ref="tns:function" minOccurs="0" maxOccurs="unbounded"/>
			</sequence>
			<attribute name="source" type="string" use="required" />
			<attribute name="as" type="tns:asAttribute" use="optional" />
			<attribute name="name" type="string" use="optional"></attribute>
			<attribute name="value" type="string" use="optional"></attribute>

		</complexType>
	</element>

	<element name="constant">
		<complexType>
			<attribute name="value" type="string" use="required" />
		</complexType>
	</element>

	<element name="regexp">
		<complexType>
			<attribute name="match" type="string" use="required" />
			<attribute name="format" type="string" use="optional" />
			<attribute name="exceptionOnFail" type="boolean" use="optional"
				default="false"></attribute>
		</complexType>
	</element>

	<element name="lookup">
		<complexType>
			<attribute name="in" type="string" use="required" />
		</complexType>
	</element>

	<element name="replace">
		<complexType>
			<attribute name="pattern" type="string" use="required" />
			<attribute name="with" type="string" use="required" />
		</complexType>
	</element>

	<element name="compose">
		<complexType>
			<attribute name="prefix" type="string" use="optional" />
			<attribute name="postfix" type="string" use="optional" />
		</complexType>
	</element>

	<element name="isbn">
		<complexType>
			<attribute name="to" type="tns:toIsbnAttribute" use="required" />
			<attribute name="verifyCheckDigit" type="boolean" use="optional"
				default="false"></attribute>
		</complexType>
	</element>


	<element name="map">
		<complexType>
			<sequence>
				<element ref="tns:entry" minOccurs="0" maxOccurs="unbounded" />
			</sequence>
			<attribute name="name" type="string" use="required" />
			<attribute name="default" type="string" use="optional" />
		</complexType>
	</element>

	<element name="entry">
		<complexType>
			<attribute name="name" type="string" use="required" />
			<attribute name="value" type="string" use="required" />
		</complexType>
	</element>

	<simpleType name="toIsbnAttribute">
		<restriction base="string">
			<enumeration value="isbn13" />
			<enumeration value="isbn10" />
			<enumeration value="clean" />
		</restriction>
	</simpleType>

	<simpleType name="asAttribute">
		<restriction base="string">
			<enumeration value="name" />
			<enumeration value="value" />
		</restriction>
	</simpleType>


	<element name="entity">
		<complexType>
			<attribute name="name" type="string" use="required" />
			<attribute name="on" type="string" use="required" />
		</complexType>
	</element>

	<element name="substring">
		<complexType>
			<attribute name="start" default="0" use="optional">
				<simpleType>
					<restriction base="int">
						<minInclusive value="0"></minInclusive>
					</restriction>
				</simpleType>
			</attribute>
			<attribute name="end" use="optional" default="0">
				<simpleType>
					<restriction base="int">
						<minInclusive value="0"></minInclusive>
					</restriction>
				</simpleType>
			</attribute>
		</complexType>
	</element>

	<group name="function">
		<choice>
			<element ref="tns:compose" />
			<element ref="tns:regexp" />
			<element ref="tns:replace" />
			<element ref="tns:substring" />
			<element ref="tns:constant" />
			<element ref="tns:lookup" />
			<element ref="tns:isbn" />
		</choice>
	</group>

</schema>

=== kba/culturegraph-metamorph/src/main/resources/pica.xml
<?xml version="1.0" encoding="UTF-8"?>
<metamorph xmlns="http://www.culturegraph.org/metamorph"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="
		http://www.culturegraph.org/metamorph metamorph.xsd" entityMarker=".">

	<name>Umsetzung Title</name>

	<data source="003@.0" name="cg:sourceRecordId" />
	
	<data source="001B.0" name="dcterms:modified" />
		
	<data source="013H.0" name="dcterms:format">
	</data>
	
	<data source="010@.a" name="dcterms:language"/>
	
	<data source="019@a" name="cg:countryCodeIso" />
	
	<group name="dcterms:issued">
		<data source="011@.a" />
		<data source="011@.n" />
	</group>
	
	<data source="010@.c" name="xbib:originLanguage"/>
	
	<data source="006A.0" name="xbib:identifierAuthorityLOC" />
	
	<data source="006Y.0" name="xbib:identifierPatent" />
	
	<data source="006G.0" name="xbib:identifierAuthorityDNB" />
	
	<data source="006B.0" name="xbib:identifierAuthorityBNB" />
	
	<data source="006Z.0" name="xbib:identifierAuthorityZDB" />
	
	<data source="006X.0" name="xbib:identifierAuthorityCasaliniLibri" />
	<data source="006X.2" name="xbib:identifierAuthorityCasaliniLibri" />
	
	<data source="006A.0" name="xbib:identifierAuthorityLOC" />
	
	<data source="006X.2" name="xbib:identifierAuthorityCasaliniLibri" />
	
	<collect-literal name="xbib:identifierAuthorityEKI"
		value="${prefix}${id}">
		<data source="007G.a" name="prefix" />
		<data source="007G.0" name="id"/>
	</collect-literal>	
				
	<data source="007Ha.0" name="xbib:identifierRegioKOBV" />
	<data source="007Hd.0" name="xbib:identifierRegioHBZ" />
	<data source="007He.0" name="xbib:identifierRegioHEBIS" />
	<data source="007Hf.0" name="xbib:identifierRegioBSZ" />
	<data source="007Hg.0" name="xbib:identifierRegioBVB" />
	<data source="007Hh.0" name="xbib:identifierRegioGBV" />
			
	<data source="007Ib.0" name="xbib:identifierAuthorityBNB" />
	<data source="007Ic.0" name="xbib:identifierAuthorityCasaliniLibri" />
	<data source="007Ie.0" name="xbib:identifierAuthorityEKZ" />
	<data source="007Ig.0" name="xbib:identifierAuthorityBNF" />
	<data source="007Il.0" name="xbib:identifierAuthorityLOC" />
	<data source="007Io.0" name="xbib:identifierAuthorityOCLC" />
		
	<data source="004A.0" name="xbib:identifierAuthorityISBN">
		<isbn to="isbn13" />
	</data>
	
	<data source="005A.0" name="xbib:identifierAuthorityISSN" />
	
	<data source="004F.0" name="xbib:identifierAuthorityISMN" />
	
	<data source="004M.0" name="xbib:identifierAuthorityISRN" />
	
	<data source="004L.0" name="xbib:identifierAuthorityEAN" />
	
	<data source="004V.0" name="xbib:uniformResourceDoi" />
	
	<data source="004U.0" name="xbib:uniformResourceName" />
	
	<data source="004R.0" name="xbib:uniformResourceHandle" />
	
	<data source="007E.0" name="xbib:identifierUniversityScript"/>
	
	<data source="006W.0" name="xbib:identifierVD18"/>
	
	<data source="006V.0" name="xbib:identifierVD16"/>
	
	<data source="006R.0" name="xbib:identifierVD17"/>
	
	<data source="007P.0" name="xbib:fingerprint"/>
	
	<group name="xbib:creatorDNBGND">
		<data source="028A.9" />
		<data source="028A.7" />
	</group>
		
	<collect-literal name="dcterms:creator"
		value="${surname}${forename}${prefix}${personalname}${qualifier}"
		forceOnEnd="028A">
		<data source="028A.a" name="surname" />
		<data source="028A.d" name="forename">
			<compose prefix=", " />
		</data>
		<data source="028A.c" name="prefix">
			<compose prefix=" " />
		</data>
		<data source="028A.l" name="qualifier">
			<compose prefix=" &lt;" postfix="&gt;" />
		</data>
		<data source="028A.5" name="personalname" />
	</collect-literal>
	
	<group name="rdaGr2:identifierForTheCorporateBody">
		<data source="029A.9" />
		<data source="029A.0" />
	</group>

	<group name="gnd:preferredNameForTheCorporateBody">
		<data source="029A.a" />
		<data source="029A.b" />
	</group>
	
	<group name="dcterms:title">
		<data source="021A.a" />
	</group>
	
	<group name="xbib:issueType">
		<data source="032@.a" />
	</group>
	
	
	<data source="002@.0" name="cg:typeOfWork">
	<substring start="1" end="2"/>
		<lookup in="workList" />
	</data>
	
	<data source="002@.0" name="cg:statusWork">
	<substring start="2" end="3"/>
		<lookup in="statusList" />
	</data>
					
	<data source="033A.p" name="xbib:publicationPlace" />
	<data source="033A.n" name="xbib:publisherName" />
	
	<map name="workList">
		<entry name="a" value="independentWork" />
		<entry name="b" value="journalSeriesNewspaper" />
		<entry name="c" value="severalVolumesWorkLimited" />
		<entry name="d" value="journalSeriesNewspaper" />
		<entry name="E" value="severalVolWorkLtdPartOfBigger " />
		<entry name="f" value="dependentConWork" />
		<entry name="F" value="singleVolumeWorkPartOfBigger" />
		<entry name="l" value="journalSeriesNewspaper" />
		<entry name="p" value="journalSeriesNewspaper" />
	</map>
	
		<map name="statusList">
		<entry name="a" value="provisorischerDatensatz" />
		<entry name="c" value="DatensatzNeuerscheinungsdienst" />
		<entry name="d" value="HssReiheH" />
		<entry name="f" value="Fremddaten" />
		<entry name="g" value="konvDatensHss " />
		<entry name="h" value="konvZeitschriftenDaten" />
		<entry name="l" value="konvDaten" />
		<entry name="r" value="konvDaten" />
		<entry name="s" value="konvDaten" />
		<entry name="n" value="altDaten" />
		<entry name="o" value="altDaten" />
		<entry name="t" value="altDaten" />
	</map>
	
</metamorph>

=== kba/culturegraph-metamorph/src/main/resources/pnd_function.pica.xml
<?xml version="1.0" encoding="UTF-8"?>
<metamorph xmlns="http://www.culturegraph.org/metamorph"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:my="http://www.dnb.de/myfunctions"
	xsi:schemaLocation="
		http://www.culturegraph.org/metamorph metamorph.xsd"
	entityMarker=".">

	<name>Umsetzung der PND</name>


	<function name="my:compose" class="org.culturegraph.metamorph.functions.Compose"/>

	<group name="rdaGr2:identifierForThePerson">
		<data source="007Q.0">
			<compose prefix="(DE-588c)" />
		</data>
		<data source="007T.0">
			<compose prefix="(DLC)" />
		</data>
		<data source="003@.0">
			<compose prefix="(DE-588a)" />
		</data>
	</group>


	<data source="028A.a" name="surname" >
		<my:compose prefix="GURK"/>
	</data>
	


	<collect-literal name="gnd:variantNameForThePerson"
		value="${surname}${forename}${prefix}${personalname}${qualifier}"
		forceOnEnd="028A">
		<data source="028A.a" name="surname" />
		<data source="028A.d" name="forename">
			<compose prefix=", " />
		</data>
		<data source="028A.c" name="prefix">
			<compose prefix=" " />
		</data>
		<data source="028A.l" name="qualifier">
			<compose prefix=" &lt;" postfix="&gt;" />
		</data>
		<data source="028A.5" name="personalname" />
	</collect-literal>

	<data name="rdaGr2:dateOfBirth" source="032Aa.a">
		<replace pattern=" " with="" />
		<regexp match="((\d*?))-" format="${1}" />
	</data>

	<data name="rdaGr2:dateOfDeath" source="032Aa.a">
		<replace pattern=" " with="" />
		<regexp match="-((\d*?))$" format="${1}" />
	</data>



</metamorph>

=== kba/culturegraph-metamorph/src/main/resources/marc21.xml
<?xml version="1.0" encoding="UTF-8"?>
<metamorph xmlns="http://www.culturegraph.org/metamorph"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="
		http://www.culturegraph.org/metamorph metamorph.xsd">

	<name>Marc21 to PropertyRecord</name>
	<annotation></annotation>

    <data source="001" name="cg:sourceRecordId" ></data>
	
	<data source="0167 .2" name="xbib:identifierAuthority" />
	<data source="0167 .a" name="xbib:identifierAuthority" />
	
	<data source="010  .a" name="xbib:identifierAuthorityLOC" />
	<data source="035  .a" name="xbib:identifierAuthorityEKI" />
	<data source="0242 .a" name="xbib:identifierAuthorityISMN" />
	<data source="022  .a" name="xbib:identifierAuthorityISSN" />
	<data source="027  .a" name="xbib:identifierAuthorityISRN" />
	
	 	 	
	<data source="020  .a" name="xbib:identifierAuthorityISBN">
		<isbn to="clean" />
	</data>

</metamorph>

=== kba/culturegraph-metamorph/src/main/resources/ingest2.pica.xml
<?xml version="1.0" encoding="UTF-8"?>
<metamorph xmlns="http://www.culturegraph.org/metamorph"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="
		http://www.culturegraph.org/metamorph metamorph.xsd"
	entityMarker=".">

	<name>PicaPlus to PropertyRecord</name>
	

	<data source="002@.0" name="cg:modeOfIssuance">
		<substring start="1" end="2" />
		<lookup in="workList" />
	</data>

	<data source="002@.0" name="dcterms:format">
		<substring start="0" end="1" />
		<lookup in="material" />
	</data>

	<data source="003@.0" name="cg:sourceRecordId" />

	<data source="004A.0" name="bibo:isbn">
		<isbn to="isbn13" />
	</data>

	<data source="004F.0" name="cg:idISMN" />

	<data source="004K.0" name="bibo:gtin14 " />

	<data source="004M.0" name="cg:isrn" />

	<data source="004P.0" name="bibo:doi" />

	<data source="004U.0" name="cg:uniformResourceName" />

	<data source="004R.0" name="bibo:handle" />

	<data source="005I.0" name="bibo:issn" />
	

	<group name="cg:dnb">
		<data source="006Y.0" />
		<data source="003@.0" />
	</group>

	<data source="006Z.0" name="cg:zdb" />
<!--  
	<data source="006Y.0" name="xbib:identifierPatent" />
	
	<data source="006W.0" name="xbib:identifierVD18" />

	<data source="006V.0" name="xbib:identifierVD16" />

	<data source="006R.0" name="xbib:identifierVD17" />
-->
	<collect-literal name="cg:eki"
		value="${prefix}${id}">
		<data source="007G.a" name="prefix" />
		<data source="007G.0" name="id" />
	</collect-literal>

	<data source="007Ha.0" name="cg:idRegioKOBV" />
	<data source="007Hd.0" name="cg:idRegioHBZ" />
	<data source="007He.0" name="cg:idRegioHEBIS" />
	<data source="007Hf.0" name="cg:idRegioBSZ" />
	<data source="007Hg.0" name="cg:idRegioBVB" />
	<data source="007Hh.0" name="cg:idRegioGBV" />

	<data source="007Ib.0" name="cg:bnb" />
	<data source="007Ic.0" name="cg:casalini" />
	<data source="007Ie.0" name="cg:ekz" />
	<data source="007Ig.0" name="cg:bnf" />
	<data source="007Il.0" name="cg:loc" />
	<data source="007Io.0" name="cg:oclc" />

	<data source="007E.0" name="cg:idUniversityScript" />

	<!--  <data source="007P.0" name="xbib:fingerprint" /> -->

	<data source="010@.a" name="dcterms:language" />

	<data source="010@.c" name="cg:originLanguage" />

	<group name="dcterms:issued">
		<data source="011@.a" />
		<data source="011@.n" />
	</group>

	<!--  <data source="013H.0" name="dcterms:format">	</data> -->

	<data source="019@a" name="cg:countryCodeIso" />

	<group name="@dcterms:title">
		<data source="021A.a" />
		<data source="021B.a" />
	</group>

	<data source="@dcterms:title" name="dcterms:title">
		<normalize-utf8 />
	</data>

	<group name="@cg:additionToTitle">
		<data source="021A.d" />
		<data source="021B.d" />
	</group>

	<data source="@cg:additionToTitle" name="cg:additionToTitle">
		<normalize-utf8 />
	</data>


	<data source="021A.9" name="cg:broaderWorkId" />

	<data source="021B.l" name="bibo:volume" />

	<data source="032@.a" name="cg:edition" />

	<group name="cg:creatorDNBGND">
		<data source="028A.9" />
		<data source="028A.7" />
	</group>

	<collect-literal name="dcterms:creator"
		value="${surname}${forename}${prefix}${personalname}${qualifier}"
		forceOnEnd="028A">
		<data source="028A.a" name="surname" />
		<data source="028A.d" name="forename">
			<compose prefix=", " />
		</data>
		<data source="028A.c" name="prefix">
			<compose prefix=" " />
		</data>
		<data source="028A.l" name="qualifier">
			<compose prefix=" &lt;" postfix="&gt;" />
		</data>
		<data source="028A.5" name="personalname" />
	</collect-literal>

	<group name="rdaGr2:identifierForTheCorporateBody">
		<data source="029A.0" />
	</group>

	<group name="cg:identifierForTheSecondaryCorporateBody">
		<data source="029F.0" />
	</group>

	<group name="gnd:preferredNameForTheCorporateBody">
		<data source="029A.a" />
		<data source="029A.b" />
	</group>

	<data source="033A.p" name="cg:publicationPlace" />
	<data source="033A.n" name="dc:publisher" />

	<data source="034D.a" name="dcterms:extent" />
	
	<group name="dcterms:isPartOf">
		<data source="021A.9" />
		<data source="036D.9" />
		<data source="036F.9" />
		<data source="039B.9" />
		<data source="039C.9" />
	</group>
	
	<data source="034D.9" name="dc:isFormatOf" />
	
	<map name="workList">
		<entry name="a" value="bibo:Document" />
		<entry name="b" value="bibo:Periodical" /> 
		<entry name="c" value="bibo:Collection" />
		<entry name="d" value="bibo:Series" />
		<entry name="E" value="bibo:Collection" />
		<entry name="F" value="bibo:Document" />
		<entry name="f" value="bibo:Document" /> 
		<entry name="l" value="bibo:Periodical" />
	</map>
	
	<map name="material">
		<entry name="A" value="print" />
		<entry name="B" value="audiovisual" />
		<entry name="C" value="brailles" />
		<entry name="E" value="microfiches" />
		<entry name="K" value="maps" />
		<entry name="O" value="online" />
		<entry name="S" value="discs" />
		<entry name="Z" value="multimedia" />
	</map>
	<!-- <map name="statusList"> <entry name="a" value="provisorischerDatensatz" 
		/> <entry name="c" value="DatensatzNeuerscheinungsdienst" /> <entry name="d" 
		value="HssReiheH" /> <entry name="f" value="Fremddaten" /> <entry name="g" 
		value="konvDatensHss " /> <entry name="h" value="konvZeitschriftenDaten" 
		/> <entry name="l" value="konvDaten" /> <entry name="r" value="konvDaten" 
		/> <entry name="s" value="konvDaten" /> <entry name="n" value="altDaten" 
		/> <entry name="o" value="altDaten" /> <entry name="t" value="altDaten" /> 
		</map> -->

</metamorph>

=== kba/culturegraph-metamorph/src/main/resources/chooseLiteral.pica.xml
<?xml version="1.0" encoding="UTF-8"?>
<metamorph xmlns="http://www.culturegraph.org/metamorph"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="
		http://www.culturegraph.org/metamorph metamorph.xsd"
	entityMarker=".">

	<name></name>
	<annotation></annotation>

	<!-- <choose-literal forceOnEnd="028@"> -->
	<!-- <data source="028@.5" /> -->
	<!-- <data source="028@.a" /> -->
	<!-- </choose-literal> -->

	<collect-literal name="@temp" value="${surname1}${surname2}"
		sameEntity="true">
		<data name="surname1" source="028A.a" />
		<data name="surname2" source="028A.a" />
		<lookup in="map"/>
	</collect-literal>

	<collect-literal name="${temp}" value="${forename}"
		sameEntity="true">
		<data name="temp" source="@temp" />
		<data name="forename" source="028A.d" />
	</collect-literal>
	

	<map name="map">
		<entry name="HussellHussell" value="Hussell Entity" />
	</map>

</metamorph>

=== kba/culturegraph-metamorph/src/main/resources/picaTitle.xml
<?xml version="1.0" encoding="UTF-8"?>
<metamorph xmlns="http://www.culturegraph.org/metamorph"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="
		http://www.culturegraph.org/metamorph metamorph.xsd" entityMarker=".">

	<name>Umsetzung Title</name>

	<data source="003@.0" name="cg:sourceRecordId" />
	
	<data source="001B.0" name="dcterms:modified" />
		
	<data source="013H.0" name="dcterms:format">
	</data>
	
	<data source="010@.a" name="dcterms:language"/>
	
	<data source="019@a" name="cg:countryCodeIso" />
	
	<data source="011@.a" name="dcterms:issued"/>
	
	<data source="010@.c" name="xbib:originLanguage"/>
	
	<data source="006A.0" name="xbib:identifierAuthorityLOC" />
	
	<data source="006Y.0" name="xbib:identifierPatent" />
	
	<data source="006G.0" name="xbib:identifierAuthorityDNB" />
	
	<data source="006B.0" name="xbib:identifierAuthorityBNB" />
	
	<data source="006Z.0" name="xbib:identifierAuthorityZDB" />
	
	<data source="006X.0" name="xbib:identifierAuthorityCasaliniLibri" />
	<data source="006X.2" name="xbib:identifierAuthorityCasaliniLibri" />
	
	<data source="006A.0" name="xbib:identifierAuthorityLOC" />
	
	<data source="006X.2" name="xbib:identifierAuthorityCasaliniLibri" />
	
	<data source="007Ga.0" name="xbib:identifierRegioKOBV" />
			
	<data source="007Ha.0" name="xbib:identifierRegioKOBV" />
	<data source="007Hd.0" name="xbib:identifierRegioHBZ" />
	<data source="007He.0" name="xbib:identifierRegioHEBIS" />
	<data source="007Hf.0" name="xbib:identifierRegioBSZ" />
	<data source="007Hg.0" name="xbib:identifierRegioBVB" />
	<data source="007Hh.0" name="xbib:identifierRegioGBV" />
			
	<data source="007Ib.0" name="xbib:identifierAuthorityBNB" />
	<data source="007Ic.0" name="xbib:identifierAuthorityCasaliniLibri" />
	<data source="007Ie.0" name="xbib:identifierAuthorityEKZ" />
	<data source="007Ig.0" name="xbib:identifierAuthorityBNF" />
	<data source="007Il.0" name="xbib:identifierAuthorityLOC" />
	<data source="007Io.0" name="xbib:identifierAuthorityOCLC" />
		
	<data source="004A.0" name="xbib:identifierAuthorityISBN">
		<isbn to="isbn13" />
	</data>
	
	<data source="005A.0" name="xbib:identifierAuthorityISSN" />
	
	<data source="004F.0" name="xbib:identifierAuthorityISMN" />
	
	<data source="004M.0" name="xbib:identifierAuthorityISRN" />
	
	<data source="004L.0" name="xbib:identifierAuthorityEAN" />
	
	<data source="004V.0" name="xbib:uniformResourceDoi" />
	
	<data source="004U.0" name="xbib:uniformResourceName" />
	
	<data source="004R.0" name="xbib:uniformResourceHandle" />
	
	<data source="007E.0" name="xbib:identifierUniversityScript"/>
	
	<data source="006W.0" name="xbib:identifierVD18"/>
	
	<data source="006V.0" name="xbib:identifierVD16"/>
	
	<data source="006R.0" name="xbib:identifierVD17"/>
	
	<data source="007P.0" name="xbib:fingerprint"/>
	
	
</metamorph>

=== kba/culturegraph-metamorph/src/main/resources/pnd.pica.xml
<?xml version="1.0" encoding="UTF-8"?>
<metamorph xmlns="http://www.culturegraph.org/metamorph"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="
		http://www.culturegraph.org/metamorph metamorph.xsd"
	entityMarker=".">

	<name>Umsetzung der PND</name>


	<group name="http://RDVocab.info/ElementsGr2/identifierForThePerson">
		<data source="007Q.0">
			<compose prefix="(DE-588c)" />
		</data>
		<data source="007T.0">
			<compose prefix="(DLC)" />
		</data>
		<data source="003@.0">
			<compose prefix="(DE-588a)" />
		</data>
	</group>

	<group name="http://d-nb.info/gnd/invalidIdentifierForThePerson">
		<data source="007G.0" />
		<data source="007Hm.0">
			<compose prefix="(DE-101c)" />
		</data>
	</group>

	<collect-entity name="http://d-nb.info/gnd/variantNameForThePerson"
		forceOnEnd="028A">
		<data name="http://d-nb.info/gnd/personalName" source="028A.5" />
		<data name="http://d-nb.info/gnd/surname" source="028A.a" />
		<data name="http://d-nb.info/gnd/forename" source="028A.d" />
		<data name="http://d-nb.info/gnd/prefix" source="028A.c" />
		<data name="http://d-nb.info/gnd/qualifier" source="028A.l" />
	</collect-entity>


	<collect-literal name="http://d-nb.info/gnd/variantNameForThePerson"
		value="${surname}${forename}${prefix}${personalname}${qualifier}"
		forceOnEnd="028A">
		<data source="028A.a" name="surname" />
		<data source="028A.d" name="forename">
			<compose prefix=", " />
		</data>
		<data source="028A.c" name="prefix">
			<compose prefix=" " />
		</data>
		<data source="028A.l" name="qualifier">
			<compose prefix=" &lt;" postfix="&gt;" />
		</data>
		<data source="028A.5" name="personalname" />
	</collect-literal>

	<data name="http://RDVocab.info/ElementsGr2/dateOfBirth" source="032Aa.a">
		<replace pattern=" " with="" />
		<regexp match="((\d*?))-" format="${1}" />
	</data>

	<data name="http://RDVocab.info/ElementsGr2/dateOfDeath" source="032Aa.a">
		<replace pattern=" " with="" />
		<regexp match="-((\d*?))$" format="${1}" />
	</data>

	<group name="http://RDVocab.info/ElementsGr2/periodOfActivityOfThePerson">
		<data source="032Ab.a" />
		<data source="032Ac.a" />
		<data source="032Ae.a" />
	</group>


	<data source="032Ba.a" name="http://RDVocab.info/ElementsGr2/placeOfBirth" />
	<data source="032Bd.a" name="http://RDVocab.info/ElementsGr2/placeOfDeath" />
	<group name="http://RDVocab.info/ElementsGr2/placeOfResidence">
		<data source="032Be.a" />
		<data source="032Bf.a" />
	</group>
	<data source="032Bq.a" name="http://RDVocab.info/ElementsGr2/titleOfThePerson" />
	<data source="032Bt.a" name="http://d-nb.info/gnd/academicTitleOfThePerson" />
	<data source="032Bu.a"
		name="http://RDVocab.info/ElementsGr2/biographicalInformation" />
	<data source="032Bw.a" name="http://RDVocab.info/ElementsGr2/gender" />
	<data source="032Bz.a" name="http://d-nb.info/gnd/studyPathsOfThePerson" />

	<data source="032Fa.9"
		name="http://RDVocab.info/ElementsGr2/professionOrOccupation">
		<compose prefix="http://d-nb.info/gnd/" />
	</data>

	<data name="rdaRelGr2:relatedCorporateBodyPerson" source="038C.9" />
	<data name="http://xmlns.com/foaf/0.1/homepage " source="009Q.u" />
	<data name="http://d-nb.info/gnd/countryCodeForThePerson" source="042B.a" />
	<data name="http://RDVocab.info/ElementsGr2/languageOfThePerson"
		source="042C.a" />
	<data name="http://www.w3.org/2002/07/owl#sameAs" source="039I.9" />
	<data name="http://d-nb.info/gnd/publicationOfThePerson" source="046G.a" />

	<map name="namespaces">
		<entry name="gnd" value="http://d-nb.info/gnd/" />
		<entry name="rdaGr2" value="http://RDVocab.info/ElementsGr2/" />
		<entry name="foaf" value="http://xmlns.com/foaf/0.1/" />
		<entry name="owl" value="http://www.w3.org/2002/07/owl#" />
	</map>

</metamorph>
