=== kba/culturegraph-metamorph/src/main/resources/metamorph.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns:tns="http://www.culturegraph.org/metamorph"
	targetNamespace="http://www.culturegraph.org/metamorph" xmlns="http://www.w3.org/2001/XMLSchema">

	<include schemaLocation="" />

	<element name="metamorph">
		<complexType>
			<sequence minOccurs="1" maxOccurs="1">
				<element ref="tns:name" maxOccurs="1" minOccurs="0" />
				<element ref="tns:annotation" maxOccurs="1" minOccurs="0" />
				<element ref="tns:entity" maxOccurs="unbounded" minOccurs="0" />
				<choice maxOccurs="unbounded" minOccurs="0">
					<element ref="tns:group" />
					<element ref="tns:collect-literal" />
					<element ref="tns:collect-entity" />
					<element ref="tns:data" />
				</choice>
				<element ref="tns:map" minOccurs="0" maxOccurs="unbounded" />
			</sequence>
			<attribute name="entityMarker">
				<simpleType>
					<restriction base="string">
						<length value="1"></length>
					</restriction>
				</simpleType>
			</attribute>
		</complexType>
	</element>

	<element name="name" type="string" />
	<element name="annotation" type="string" />

	<element name="group">
		<complexType>
			<sequence>
				<element ref="tns:annotation" minOccurs="0" maxOccurs="1" />
				<choice minOccurs="1" maxOccurs="unbounded">
					<element ref="tns:collect-literal" minOccurs="0" maxOccurs="unbounded" />
					<element ref="tns:data" minOccurs="0" maxOccurs="unbounded" />
				</choice>
			</sequence>
			<attribute name="name" type="string" use="optional" />
			<attribute name="value" type="string" use="optional" />
		</complexType>
	</element>

	<element name="collect-literal">
		<complexType>
			<sequence>
				<element ref="tns:annotation" minOccurs="0" maxOccurs="1" />
				<element ref="tns:data" minOccurs="2" maxOccurs="unbounded" />
				<group ref="tns:function" minOccurs="0" maxOccurs="unbounded"/>
			</sequence>
			<attribute name="name" type="string" use="optional" />
			<attribute name="value" type="string" use="optional" />

			<attribute name="reset" type="boolean" use="optional"
				default="false" />
			<attribute name="sameEntity" type="boolean" use="optional"
				default="false" />
			<attribute name="forceOnEnd" type="string" use="optional" />
		</complexType>
	</element>

	<element name="collect-entity">
		<complexType>
			<sequence>
				<element ref="tns:annotation" minOccurs="0" maxOccurs="1" />
				<element ref="tns:data" minOccurs="1" maxOccurs="unbounded" />
			</sequence>
			<attribute name="name" type="string" use="required" />
			<attribute name="reset" type="boolean" use="optional"
				default="false" />
			<attribute name="sameEntity" type="boolean" use="optional"
				default="false" />
			<attribute name="forceOnEnd" type="string" use="optional" />
		</complexType>
	</element>

	<element name="data">
		<complexType>
			<sequence>
				<element ref="tns:annotation" minOccurs="0" maxOccurs="1" />
				<group ref="tns:function" minOccurs="0" maxOccurs="unbounded"/>
			</sequence>
			<attribute name="source" type="string" use="required" />
			<attribute name="as" type="tns:asAttribute" use="optional" />
			<attribute name="name" type="string" use="optional"></attribute>
			<attribute name="value" type="string" use="optional"></attribute>

		</complexType>
	</element>

	<element name="constant">
		<complexType>
			<attribute name="value" type="string" use="required" />
		</complexType>
	</element>

	<element name="regexp">
		<complexType>
			<attribute name="match" type="string" use="required" />
			<attribute name="format" type="string" use="optional" />
			<attribute name="exceptionOnFail" type="boolean" use="optional"
				default="false"></attribute>
		</complexType>
	</element>

	<element name="lookup">
		<complexType>
			<attribute name="in" type="string" use="required" />
		</complexType>
	</element>

	<element name="replace">
		<complexType>
			<attribute name="pattern" type="string" use="required" />
			<attribute name="with" type="string" use="required" />
		</complexType>
	</element>

	<element name="compose">
		<complexType>
			<attribute name="prefix" type="string" use="optional" />
			<attribute name="postfix" type="string" use="optional" />
		</complexType>
	</element>

	<element name="isbn">
		<complexType>
			<attribute name="to" type="tns:toIsbnAttribute" use="required" />
			<attribute name="verifyCheckDigit" type="boolean" use="optional"
				default="false"></attribute>
		</complexType>
	</element>


	<element name="map">
		<complexType>
			<sequence>
				<element ref="tns:entry" minOccurs="0" maxOccurs="unbounded" />
			</sequence>
			<attribute name="name" type="string" use="required" />
			<attribute name="default" type="string" use="optional" />
		</complexType>
	</element>

	<element name="entry">
		<complexType>
			<attribute name="name" type="string" use="required" />
			<attribute name="value" type="string" use="required" />
		</complexType>
	</element>

	<simpleType name="toIsbnAttribute">
		<restriction base="string">
			<enumeration value="isbn13" />
			<enumeration value="isbn10" />
			<enumeration value="clean" />
		</restriction>
	</simpleType>

	<simpleType name="asAttribute">
		<restriction base="string">
			<enumeration value="name" />
			<enumeration value="value" />
		</restriction>
	</simpleType>


	<element name="entity">
		<complexType>
			<attribute name="name" type="string" use="required" />
			<attribute name="on" type="string" use="required" />
		</complexType>
	</element>

	<element name="substring">
		<complexType>
			<attribute name="start" default="0" use="optional">
				<simpleType>
					<restriction base="int">
						<minInclusive value="0"></minInclusive>
					</restriction>
				</simpleType>
			</attribute>
			<attribute name="end" use="optional" default="0">
				<simpleType>
					<restriction base="int">
						<minInclusive value="0"></minInclusive>
					</restriction>
				</simpleType>
			</attribute>
		</complexType>
	</element>

	<group name="function">
		<choice>
			<element ref="tns:compose" />
			<element ref="tns:regexp" />
			<element ref="tns:replace" />
			<element ref="tns:substring" />
			<element ref="tns:constant" />
			<element ref="tns:lookup" />
			<element ref="tns:isbn" />
		</choice>
	</group>

</schema>

=== kba/culturegraph-metamorph/src/main/resources/mab2.xml
<?xml version="1.0" encoding="UTF-8"?>
<metamorph xmlns="http://www.culturegraph.org/metamorph"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="
		http://www.culturegraph.org/metamorph metamorph.xsd">

	<name>Mab2 to PropertyRecord</name>
	<annotation></annotation>


	<data source="001" name="cg:sourceRecordId" />
	<data source="003" name="xbib:lastModifiedByInstitution" />
	<data source="025a" name="xbib:identifierAuthorityDNB" />
	<data source="025b" name="xbib:identifierAuthorityBNB" />
	<data source="025c" name="xbib:identifierAuthorityCasaliniLibri" />
	<data source="025f" name="xbib:identifierAuthorityBNF" />
	<data source="025l" name="xbib:identifierAuthorityLOC" />
	<data source="025o" name="xbib:identifierAuthorityOCLC" />
	<data source="025z" name="xbib:identifierAuthorityZDB" />
	<data source="026" name="xbib:identifierAuthorityEKI" />
	<data source="037b" name="dcterms:language" />
	<data source="089" name="xbib:titleVolume" />
	<data source="089" name="xbib:titleVolume" />
	
	<group name="xbib:creatorDNBGND">
		<data source="102a" />
		<data source="106a" />
	</group>
	
	<group name="dcterms:titleUniform">
		<data source="304" />
		<data source="304a" />
		<data source="304b" />
	</group>
	
	<group name="dcterms:title">
		<data source="310" />
		<data source="310.1" />
		<data source="310a" />
		<data source="310a.1" />
		<data source="310b" />
		<data source="310b.1" />
		<data source="331" />
		<data source="331.1" />
		<data source="331a" />
		<data source="331b" />
		<data source="333" />
		<data source="333.1" />
		<data source="360" />
		<data source="360.1" />
	</group>
	
	<data source="410" name="xbib:publicationPlace" />
	<data source="412" name="xbib:publisherName" />
	<data source="425" name="dcterms:issued" />

	<group name="dcterms:titleSeries">
		<data source="451" />
		<data source="451a" />
		<data source="451b" />
	</group>
	
	<data source="455" name="xbib:titleVolume" />

	<data source="540a" name="xbib:identifierAuthorityISBN">
		<isbn to="clean" />
	</data>

	<data source="541a" name="xbib:identifierAuthorityOriginalISMN" />
	<data source="542a" name="xbib:identifierAuthorityISSN" />
	<data source="551a" name="xbib:identifierAudioPublisher" />
	<data source="552a" name="xbib:uniformResourceDoi" />
	<data source="552b" name="xbib:uniformResourceName" />
	<data source="552c" name="xbib:uniformResourceHandle" />
	<data source="554" name="xbib:identifierUniversityScript" />
	<data source="556" name="xbib:identifierReport" />
	<data source="562" name="xbib:identifierPatent" />
	<data source="580" name="xbib:identifierVD18" />

	<collect-literal name="ISBN_YEAR_KEY" value="${isbn}-${year}" reset="true" >
		<data source="540a" name="isbn">
			<isbn to="isbn13" />
		</data>
		<data source="425" name="year"/>
	</collect-literal>

</metamorph>
